language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE subscription;'
  - npx knex migrate:latest
cache:
  directories:
    - "node_modules"
env:
  global:
    - NODE_ENV=test
    - DATABASE_HOST=localhost
    - DATABASE_USER=travis
    - DATABASE_NAME=subscription
